FROM python:3.9

ENV DASH_DEBUG_MODE True
WORKDIR /app
COPY configurator/requirements.txt .
RUN set -ex && \
    pip install -r requirements.txt
EXPOSE 8050
COPY configurator /app
COPY common /app/common
CMD ["python", "app.py"]
